export type LanguageObj = {
  label: string;
  value: string;
};

export const languagesList: LanguageObj[] = [
  // { label: "Afrikaans", value: "Afrikaans" },
  // { label: "Shqip", value: "Albanian" },
  // { label: "ኣማርኛ", value: "Amharic" },
  { label: "اَلْعَرَبِيَّةُ", value: "Arabic" },
  // { label: "հայերեն", value: "Armenian" },
  // { label: "অসমীয়া", value: "Assamese (Bengali)" },
  // { label: "Bemba", value: "Bemba" },
  // { label: "বাংলা", value: "Bengali" },
  // { label: "Bulgarian", value: "Bulgarian" },
  // { label: "Bantu", value: "Bulu" },
  // { label: "ဗမာစကား", value: "Burmese" },
  // { label: "Català", value: "Catalan" },
  // { label: "Cebuano", value: "Cebuano" },
  // { label: "Chichewa/Nyanja", value: "Chewa" },
  { label: "正體字", value: "Chinese" },
  // { label: "Kreyòl ayisyen", value: "Creole" },
  // { label: "Hrvatski", value: "Croatian" },
  { label: "Čeština", value: "Czech" },
  // { label: "Dansk", value: "Danish" },
  // { label: "درى", value: "Dari Dialect (Afghanistan)" },
  { label: "Nederlands", value: "Dutch" },
  { label: "English", value: "English" },
  // { label: "Eesti", value: "Estonian" },
  // { label: "Ewe", value: "Ewe" },
  // { label: "Falam", value: "Falam" },
  // { label: "Suomi", value: "Finnish" },
  { label: "Français", value: "French" },
  // { label: "Fulfulde", value: "Fula" },
  // { label: "Ga", value: "Ga" },
  // { label: "Luganda", value: "Ganda" },
  // { label: "Garo", value: "Garo" },
  // { label: "ქართული", value: "Georgian" },
  { label: "Deutsch", value: "German" },
  // { label: "Ελληνικά", value: "Greek" },
  // { label: "Greenlandic", value: "Greenlandic" },
  // { label: "ગુજરાતી", value: "Gujarati" },
  // { label: "Gusii", value: "Gusii" },
  // { label: "Hakha Chin", value: "Hakha Chin" },
  // { label: "Hausa", value: "Hausa" },
  // { label: "עברית", value: "Hebrew" },
  // { label: "Ilonggo", value: "Hiligaynon" },
  // { label: "हिन्दी", value: "Hindi" },
  // { label: "Magyar", value: "Hungarian" },
  // { label: "Íslenska", value: "Icelandic" },
  // { label: "Igbo", value: "Igbo" },
  // { label: "Ilokano", value: "Ilocano" },
  // { label: "Indonesia", value: "Indonesian" },
  // { label: "Italiano", value: "Italian" },
  // { label: "日本語", value: "Japanese" },
  // { label: "Къэбэрдеибзэ", value: "Kabardian" },
  // { label: "ಕನ್ನಡ", value: "Kannada" },
  // { label: "KiiKaonde", value: "Kaonde" },
  // { label: "Қазақ", value: "Kazakh" },
  // { label: "Khasi", value: "Khasi" },
  // { label: "ភាសាខ្មែរ", value: "Khmer" },
  // { label: "Kinyarwanda", value: "Kinyarwanda" },
  // { label: "Kirundi", value: "Kirundi" },
  // { label: "한국어", value: "Korean" },
  // { label: "کوردی", value: "Kurdish" },
  // { label: "Кыргызча", value: "Kyrgyz" },
  // { label: "Lango", value: "Lango" },
  // { label: "Latviešu", value: "Latvian" },
  // { label: "Lingála", value: "Lingala" },
  // { label: "Lietuvių", value: "Lithuanian" },
  // { label: "siLozi", value: "Lozi" },
  // { label: "Tshiluba", value: "Luba-Kasai" },
  // { label: "Nganguela", value: "Luchazi" },
  // { label: "Konzo", value: "Luhya" },
  // { label: "Chilunda", value: "Lunda" },
  // { label: "Dholuo", value: "Luo" },
  // { label: "Luvale", value: "Luvale" },
  // { label: "Македонски", value: "Macedonian" },
  // { label: "Malagasy", value: "Malagasy" },
  // { label: "Melayu", value: "Malay" },
  // { label: "മലയാളം", value: "Malayalam" },
  // { label: "मराठी", value: "Marathi" },
  // { label: "Mizo", value: "Mizo" },
  // { label: "монгол", value: "Mongolian" },
  // { label: "नेपाली", value: "Nepali" },
  // { label: "Runyankore", value: "Nkore" },
  // { label: "isiNdebele", value: "North Ndebele" },
  // { label: "Norsk", value: "Norwegian" },
  // { label: "Thok Nath", value: "Nuer" },
  // { label: "ଓଡ଼ିଆ", value: "Odia" },
  // { label: "Afaan Oromoo", value: "Oromo" },
  // { label: "Oshiwambo", value: "Ovambo" },
  // { label: "Curaçao", value: "Papiamento" },
  // { label: "پښتو", value: "Pashto" },
  // { label: "فارسی", value: "Persian" },
  // { label: "Polski", value: "Polish" },
  { label: "Português", value: "Portuguese" },
  // { label: "ਪੰਜਾਬੀ", value: "Punjabi" },
  // { label: "Pwo Karen", value: "Pwo' Karen" },
  // { label: "Runasimi", value: "Quechua" },
  // { label: "Română", value: "Romanian" },
  // { label: "Rongmei", value: "Rongmei" },
  { label: "Русский", value: "Russian" },
  // { label: "Sámegiella", value: "Samoan" },
  // { label: "Santali (Ol Chiki)", value: "Santali (Ol Chiki)" },
  // { label: "Српски", value: "Serbian" },
  // { label: "ChiShona", value: "Shona" },
  // { label: "සිංහල", value: "Sinhala" },
  // { label: "Slovenčina", value: "Slovak" },
  // { label: "Af-Soomaali", value: "Somali" },
  { label: "Español", value: "Spanish" },
  // { label: "Kiswahili", value: "Swahili" },
  // { label: "Svenska", value: "Swedish" },
  // { label: "Tagalog", value: "Tagalog" },
  // { label: "Тоҷикӣ", value: "Tajik" },
  // { label: "தமிழ்", value: "Tamil" },
  // { label: "Zomi", value: "Tedim" },
  // { label: "తెలుగు", value: "Telugu" },
  // { label: "ไทย", value: "Thai" },
  // { label: "ትግርኛ", value: "Tigrinya" },
  // { label: "ChiTonga/Lenje", value: "Tonga" },
  // { label: "Setswana", value: "Tswana" },
  // { label: "Türkçe", value: "Turkish" },
  // { label: "Turkmen", value: "Turkmen" },
  { label: "Twi", value: "Twi" },
  // { label: "Українська", value: "Ukrainian" },
  // { label: "Umbundu", value: "Umbundu" },
  // { label: "اُردُو", value: "Urdu" },
  // { label: "Ўзбек", value: "Uzbek-Cyrillic" },
  // { label: "Tiếng Việt", value: "Vietnamese" },
  // { label: "isiXhosa", value: "Xhosa" },
  // { label: "Yorùbá", value: "Yoruba" },
  // { label: "isiZulu", value: "Zulu" },
];
